Refactor to single project.
glotzerlab/hoomd-validation pull request #13
Opened 2022-10-24 17:21 UTC by joaander

## Description

Refactor multiple Flow projects into a single flow project. Use subproject keys to apply operations only to the relevant signac jobs. This is very similar **in concept** to @tommy-waltmann's original design of a tiered project approach, and only requires slight code modifications to enable.

## Motivation and context

Addresses comment https://github.com/glotzerlab/hoomd-validation/pull/8#discussion_r1002165269 .

Additionally, when we add multiple subprojects (e.g. hard_disk, patchy_triangle, etc...), this new structure will allow **both** flow's `run` and `submit` infrastructure to handle all subprojects at once (or a subset using regex selection). Supporting this for `submit` does require that we use structured operation names (as documented in `ARCHITECTURE.md`) so that users can select desired operations with regex expressions across the whole project.

## How has this been tested?

I am running the workflow on Great Lakes now, will update when complete.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/ContributorAgreement.md).
- [x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

2022-10-24 17:44 UTC, b-butler approved these changes
Looks clean to me. :+1:

2022-10-25 13:54 UTC, tommy-waltmann requested changes
I just have one quick fix and one suggestion.

2022-10-25 14:32 UTC, tommy-waltmann requested changes

2022-10-25 14:39 UTC, tommy-waltmann approved these changes

2022-10-25 14:40 UTC, merged