Bump signac and signac-flow
glotzerlab/hoomd-validation pull request #50
Opened 2023-04-25 21:45 UTC by tommy-waltmann

## Description

This PR bumps both `signac` and `signac-flow`, taking the place of #47 and #48 . It also fixes a typo in `requirements.txt`

## Motivation and context

Bumping `signac` and `signac-flow` individually will necessary cause errors, due to the major version bump in `signac` and the new version requirements established between the packages.

## How has this been tested?

If CI tests pass, we are good to go.

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

2023-04-26 13:16 UTC, joaander requested changes

2023-04-26 13:16 UTC, joaander commented on .github/workflows/requirements-test.txt
> +signac-flow==0.25.1
```suggestion
signac-flow==0.25.0
```
0.25.1 doesn't exist yet: https://pypi.org/project/signac-flow/#history

2023-04-26 13:16 UTC, joaander commented on requirements.txt
> +signac-flow >= 0.25.1
```suggestion
signac-flow >= 0.25.0
```

2023-04-26 13:36 UTC, tommy-waltmann commented
It appears that they merged a [release branch](https://github.com/glotzerlab/signac-flow/pull/742) a few days ago, but the release doesn't seem to have been made yet. The 0.25.0 release of flow had a critical bug where the -f flag couldn't be used on the command line ([see here](https://github.com/glotzerlab/signac-flow/pull/738)), so we should wait until the 0.25.1 release is made before merging this.

2023-04-26 14:37 UTC, joaander commented
This bug prevents all use of `signac-flow`? Or just the `-f` command line option? `hoomd-validation` does not rely on the `-f` option.

2023-04-26 16:08 UTC, tommy-waltmann commented
Looks like 0.25.1 is on PyPI now: https://pypi.org/project/signac-flow/

The conda-forge package should be available later today or tomorrow

2023-04-26 16:15 UTC, joaander commented
`hoomd-validation` uses PyPI.

2023-04-26 16:40 UTC, joaander commented
I reran the build. It does appear that we are using removed APIs that need updating.
```
    project = signac.init_project(root=config.project_root)
TypeError: init_project() got an unexpected keyword argument 'root'
```

2023-05-01 17:26 UTC, joaander approved these changes
Thanks!

2023-05-01 17:26 UTC, merged