Concave particle pressure validation
glotzerlab/hoomd-validation pull request #61
Opened 2023-08-21 19:56 UTC by tcmoore3

## Description

Performs cross validation using NVT and NPT simulations of a hard particle with a concave shape. Computes the pressure in NVT simulations, and then runs NPT simulations and calculates the density the mean pressure. 

## Motivation and context

Validates the implementation of the SDF-based pressure calculation where the expansive contribution to the pressure is nonzero (i.e., for non-convex hard particles).

Resolves #43

## How has this been tested?

Ran on PSC-Bridges2. Results:
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/879ca6ed-63af-4be4-b671-57c6bea2aa59)

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

2023-08-21 20:00 UTC, tcmoore3 commented
pre-commit.ci autofix

2023-08-21 20:06 UTC, tcmoore3 commented
pre-commit.ci autofix

2023-08-23 13:52 UTC, joaander requested changes
Thanks! Please post the analysis results including the `nvt_gpu` jobs (run on Great Lakes or Delta).

2023-08-23 13:52 UTC, joaander commented on hoomd_validation/init.py
> +    alj_2d, lj_fluid, lj_union, hard_disk, hard_sphere, simple_polygon
```suggestion
    alj_2d, lj_fluid, lj_union, hard_disk, hard_sphere, simple_polygon,
```
And run `pre-commit` to format one item per line.

2023-08-23 13:52 UTC, joaander commented on hoomd_validation/simple_polygon.py
> +"""Hard disk equation of state validation test."""
```suggestion
"""Simple polygon equation of state validation test."""
```

2023-08-23 13:52 UTC, joaander commented on hoomd_validation/simple_polygon.py
> +    # based on nvt sims at density = 0.75 over 32 replicas
Not all of these comment lines can be true at the same time. Remove the invalid ones.

2023-08-23 13:52 UTC, joaander commented on hoomd_validation/simple_polygon.py
> +RESTART_STEPS = RUN_STEPS // 10
```suggestion
RESTART_STEPS = RUN_STEPS // 50
```
Shorten the restart period from ~30 minutes down to ~6 (tested on cheme-hodges).

2023-09-13 18:12 UTC, tcmoore3 commented
Here are the results from the GPU jobs run on Delta.
<img width="625" alt="image" src="https://github.com/glotzerlab/hoomd-validation/assets/5814680/08a128a1-16f8-48cd-a0d8-5bbeb68c543e">

2023-09-15 17:11 UTC, joaander approved these changes
Looks good! Thanks!

2023-09-15 17:11 UTC, merged