Patchy particle pressure
glotzerlab/hoomd-validation pull request #66
Opened 2023-10-08 22:56 UTC by tcmoore3

## Description

Validate pressure computation for discontinuous pair potentials simulated with HPMC.

## Motivation and context

The pressure pressure computation for systems with discontinuous pair potentials in HPMC is currently not tested for validity but should be. 

I will add another validation test for the hard sphere + square well + square shoulder system we discussed, but I wanted to get this PR opened because the code will not change very much.

Resolves #43. 

## How has this been tested?

We discovered a conceptual error in the implementation of the SDF calculation for systems with pair potentials. We implemented a fix at https://github.com/glotzerlab/hoomd-blue/commit/8d7cb2c7f3c6abf3326aeea6ca26af5a062057f5. That commit is the version of HOOMD-blue I used to generate the results below.

I ran NVT simulations of 4,096 particles interacting either through a hard sphere + square well potential, or through a Kern–Frenkel potential, i.e., a hard sphere + square well model with an angular component to the pair potential. I ran NVT simulations, measured the pressure for the given density and temperature, and then ran NPT simulations at the corresponding pressure. The agreement between the pressure measured in NVT simulations and the density measured at the corresponding NPT simulations is shown in the figures below. These results are from 16 replicates at each statepoint. \chi = 1.0 corresponds to the hard sphere + square well state points, and \chi = 0.7 is the Kern–Frenkel model.

![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/1d8fe3b4-5e83-4cea-8644-4b10aa3346ab)
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/294d11bb-9a69-47a4-adf8-8edcb925a0fb)
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/da6dee79-0903-4d51-9c70-4ffce455a746)
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/d5d63e85-db00-4c07-9680-0e7d2f797915)
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/e3f8860e-f1e1-4070-ad64-e30914f8308e)

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/ContributorAgreement.md).
- [x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

2023-10-09 15:10 UTC, joaander commented
With short simulations, I tested:
```
sigma = 1.0
lambda_ = 1.5
epsilon = 1/3.0
```
with patch code:
```
    evaluate_square_well = f'''float rsq = dot(r_ij, r_ij);
                               if (rsq < {(lambda_ * sigma/2)**2}f)
                                   return param_array[0];
                               else if (rsq < {(lambda_ * sigma)**2}f)
                                   return param_array[1];
                               else
                                   return 0.0f;
                            '''
    square_well = hoomd.hpmc.pair.user.CPPPotential(r_cut=lambda_ * sigma,
                                                    code=evaluate_square_well,
                                                    param_array=[-epsilon, epsilon])
```
at a variety of pressures (2-10) and densities (around ~0.7).

2023-10-09 15:34 UTC, joaander requested changes
I see you have GPU jobs definitions in the workflow. Do you plan to validate that these work properly before merging?

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/config_parser.py
>          self["max_walltime"] = int(config.get("max_walltime", 24))
```suggestion
        self["max_walltime"] = float(config.get("max_walltime", 24))
```
For consistency with the below change.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/init.py
> +#    simple_polygon,
```suggestion
   alj_2d,
   lj_fluid,
   lj_union,
   hard_disk,
   hard_sphere,
   simple_polygon,
```

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/init.py
> +    patchy_particle_pressure
```suggestion
    patchy_particle_pressure,
```

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +def run_up_to_walltime(sim, end_step, steps, walltime_stop, minutes_per_run=None):
```suggestion
def run_up_to_walltime(sim, end_step, steps, walltime_stop):
```
unused.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +            XX, YY = histogram, bin_centers #bin_edges[:-1]
Remove the need for the variables by placing the call to `plot` inside the conditional.

Alternately, replace meaningless XX and YY variable names with something meaningful.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +            ax.set_ylabel(xlabel)
The `xlabel` is no longer the x label. Change the name of the argument appropriately.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +            #Y, X = bin_edges[:-1], expected(bin_edges[:-1])
Remove commented code.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +            XX, YY = bin_edges[:-1], histogram
The unrotated plot should also use `bin_centers`.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +            X, Y = bin_edges[:-1], expected(bin_edges[:-1])
The unrotated plot should also use `bin_centers`.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +            Y, X = bin_centers, expected(bin_centers)
Remove the need for the variables by placing the call to `plot` inside the conditional.

Alternately, name these variables with a PEP8 compliant name.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/util.py
> +def _single_patch_kern_frenkel_code(delta_rad, lambda_, sigma, kT):
Move this function to `patchy_particle_pressure.py`.

2023-10-09 15:34 UTC, joaander commented on hoomd_validation/patchy_particle_pressure.py
> +    #@Project.post(lambda j: j.isfile(f'{mode}_{device_name}_complete') or j.sp.pressure <= 0)
```suggestion
```

2023-10-10 13:47 UTC, tcmoore3 commented
Results for the hard sphere + square well + repulsive shoulder potential. It shows similar quantitative agreement NPT and NVT simulations as the Kern–Frenkel and hard sphere + square well systems. 
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/bed8fda5-79f9-471d-95cc-78b1259b13b3)

2023-10-10 19:17 UTC, joaander requested changes
More fixes to prevent deadlock.

2023-10-10 19:17 UTC, joaander commented on hoomd_validation/patchy_particle_pressure.py
> +                  f'{job} in {communicator.walltime} s')
```suggestion
            print(f'completed patchy_particle_pressure_{mode}_{device_name}: {job}')
```
See #67.

2023-10-10 19:17 UTC, joaander commented on hoomd_validation/patchy_particle_pressure.py
> +              f'{job} in {communicator.walltime} s')
```suggestion
        print(f'completed patchy_particle_pressure_create_initial_state: {job}')
```
See #67.

2023-10-19 20:32 UTC, tcmoore3 commented
GPU results from 8 replicates at each of 3 statepoints, 1 KF, 1 HSSW, 1 HSSW with a repulsive shoulder. Note that I took the average pressure from the CPU NVT runs, so the deviation from the expected pressure in the 'nvt_gpu' runs are nonzero.
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/0012fadd-6164-47ce-b190-3f9758d674a1)
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/2e1e325d-0f07-4671-ada8-802287879a19)
![image](https://github.com/glotzerlab/hoomd-validation/assets/5814680/a6a3f96d-872e-43da-b91a-8e879f3de9ba)

2023-10-20 16:35 UTC, joaander requested changes
Thanks! There is one minor change to make, then this is ready to merge.

2023-10-20 16:35 UTC, joaander commented on hoomd_validation/patchy_particle_pressure.py
> +        # (1.0, 0.7, -5.0, 1.0, 1.0, -1.0),
```suggestion
        (1.0, 0.95, 10.208625410213362, 0.7, 1.5, 1.0),
        # hard sphere + square well statepoints, from 10.1063/1.3054361
        # pressure from NVT simulations, NOT from values in paper
        (3.0, 0.8, 4.837436833423719, 1.0, 1.5, 1.0),
        # hard sphere + square well + repulsive shoulder statepoints.
        # temperatures/densities from initial tests, pressures from NVT
        # simulations.
        (3.0, 0.7, 4.00804, 1.0, 1.0, -1.0),
```
Remove unused state points.

2023-10-23 13:40 UTC, joaander approved these changes
Thanks!

2023-10-23 13:41 UTC, merged