Use HDF5 files for quantity logs.
glotzerlab/hoomd-validation pull request #72
Opened 2023-11-06 13:36 UTC by joaander

## Description

Switch from GSD to HDF5 for thermodynamic logs.

## Motivation and context

Reduce the time needed to run the analysis workflow steps.

## How has this been tested?

- [ ] Test entire workflow run.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/ContributorAgreement.md).
- [x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

2023-11-07 20:22 UTC, joaander commented
I ran the complete workflow on Great Lakes. I didn't measure before/after timings, but the analysis step feels faster. The total output file size is also much smaller: 81M for 4 replicates.

2023-11-09 14:20 UTC, tommy-waltmann requested changes
The changes look mostly good. There is just one comment which appears to have been copy/pasted in each validation test file which is no longer true.

2023-11-09 14:20 UTC, tommy-waltmann commented on hoomd_validation/hard_disk.py
> +    logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
The comment above this line is no longer true.

2023-11-09 14:20 UTC, tommy-waltmann commented on hoomd_validation/hard_sphere.py
> +    logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
see above comment.

2023-11-09 14:20 UTC, tommy-waltmann commented on hoomd_validation/hard_sphere.py
> +    logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
see above comment.

2023-11-09 14:20 UTC, tommy-waltmann commented on hoomd_validation/simple_polygon.py
> +    logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
see above comment.

2023-11-09 14:20 UTC, tommy-waltmann commented on hoomd_validation/patchy_particle_pressure.py
> +    logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
see above comment.

2023-11-09 14:20 UTC, tommy-waltmann commented on hoomd_validation/lj_union.py
> +    logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
see above comment.

2023-11-09 14:20 UTC, tommy-waltmann commented on hoomd_validation/lj_fluid.py
> +    logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
see above comment.

2023-11-09 14:39 UTC, tommy-waltmann approved these changes

2023-11-09 14:39 UTC, merged